<x-app-layout>
    <x-slot name="header"><h2 class="text-2xl font-black text-cyan-200">契約・解約</h2></x-slot>
    <div class="min-h-screen bg-slate-100 py-8"><div class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        @if(session('success'))<p class="mb-4 rounded bg-emerald-50 p-4 font-bold text-emerald-800">{{ session('success') }}</p>@endif
        @if(session('error'))<p class="mb-4 rounded bg-red-50 p-4 font-bold text-red-800">{{ session('error') }}</p>@endif
        <section class="rounded bg-white p-6 shadow"><p class="text-sm font-bold text-slate-500">FurimaDeck Premium</p><p class="mt-2 text-3xl font-black text-slate-900">月額 ¥{{ number_format($price) }}</p><p class="mt-2 text-sm font-bold text-slate-700">{{ $trialDays }}日間の無料お試し</p>@if($user->hasActiveSubscription())<p class="mt-5 font-bold text-emerald-700">契約状態: {{ $user->subscription_status ?? 'active' }}</p><form method="POST" action="{{ route('furimadeck-billing.portal') }}" class="mt-5">@csrf<button class="rounded bg-slate-800 px-4 py-2 font-bold text-white">Stripeで契約を管理</button></form>@else<form method="POST" action="{{ route('furimadeck-billing.checkout') }}" class="mt-5 space-y-4">@csrf<label class="flex items-start gap-2 text-sm text-slate-700"><input required type="checkbox" name="billing_terms_confirmed" value="1" class="mt-1">料金、無料期間終了後の月額課金、自動更新、Stripeの契約管理画面で解約できることを確認しました。</label>@error('billing_terms_confirmed')<p class="font-bold text-red-700">{{ $message }}</p>@enderror<button class="rounded bg-cyan-500 px-4 py-2 font-black text-slate-950 hover:bg-cyan-400">無料お試しを開始</button></form>@endif</section>
        <section class="mt-6 rounded bg-white p-6 shadow"><h3 class="text-lg font-black text-slate-900">請求書</h3>@if($invoiceLoadFailed)<p class="mt-3 text-sm font-bold text-amber-800">請求書を取得できませんでした。時間をおいて再度お試しください。</p>@elseif($invoices === [])<p class="mt-3 text-sm font-bold text-slate-600">表示できる請求書はありません。</p>@else<div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b text-slate-500"><tr><th class="pb-2">請求書番号</th><th class="pb-2">支払日</th><th class="pb-2">金額</th><th class="pb-2">状態</th><th class="pb-2"></th></tr></thead><tbody>@foreach($invoices as $invoice)<tr class="border-b border-slate-100 text-slate-800"><td class="py-3 font-bold">{{ $invoice['number'] }}</td><td class="py-3">{{ $invoice['paidAt'] ?? '-' }}</td><td class="py-3">¥{{ number_format($invoice['amountPaid']) }}</td><td class="py-3">{{ $invoice['status'] }}</td><td class="py-3 text-right">@if($invoice['pdfUrl'])<a href="{{ $invoice['pdfUrl'] }}" target="_blank" rel="noopener noreferrer" class="font-bold text-cyan-700 hover:text-cyan-900">PDF</a>@elseif($invoice['hostedUrl'])<a href="{{ $invoice['hostedUrl'] }}" target="_blank" rel="noopener noreferrer" class="font-bold text-cyan-700 hover:text-cyan-900">表示</a>@endif</td></tr>@endforeach</tbody></table></div>@endif</section>
    </div></div>
</x-app-layout>
