<x-app-layout>
    <x-slot name="header"><h2 class="text-2xl font-black text-cyan-200">CSV取込プレビュー</h2></x-slot>
    <div class="min-h-screen bg-slate-100 py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <section class="rounded bg-white p-5 shadow"><div class="grid gap-3 sm:grid-cols-3"><p class="font-bold text-slate-800">全{{ number_format($batch->total_rows) }}行</p><p class="font-bold text-emerald-700">有効 {{ number_format($batch->success_rows) }}行</p><p class="font-bold text-red-700">エラー {{ number_format($batch->failed_rows) }}行</p></div></section>
        @if($batch->status === 'preview' && $batch->failed_rows === 0)<section class="mt-6 rounded bg-white p-5 shadow"><form method="POST" action="{{ route('products.imports.commit', $batch) }}">@csrf<button class="rounded bg-cyan-500 px-4 py-2 text-sm font-black text-slate-950 hover:bg-cyan-400" onclick="return confirm('このCSVの{{ $batch->success_rows }}件を商品として登録しますか？')">{{ $batch->success_rows }}件を登録</button></form></section>@endif
        @error('csv_file')<p class="mt-4 font-bold text-red-700">{{ $message }}</p>@enderror
        <section class="mt-6 overflow-x-auto rounded bg-white shadow"><table class="w-full text-left text-sm text-slate-800"><thead class="bg-slate-100"><tr><th class="p-3">行</th><th class="p-3">SKU</th><th class="p-3">商品名</th><th class="p-3">検証結果</th></tr></thead><tbody>@foreach($rows as $row)<tr class="border-t"><td class="p-3">{{ $row->row_number }}</td><td class="p-3 font-mono">{{ $row->row_json['internal_sku'] ?? '-' }}</td><td class="p-3">{{ $row->row_json['product_name'] ?? '-' }}</td><td class="p-3">@if($row->is_valid)<span class="font-bold text-emerald-700">有効</span>@else<ul class="list-disc ps-4 font-bold text-red-700">@foreach($row->errors_json ?? [] as $error)<li>{{ $error }}</li>@endforeach</ul>@endif</td></tr>@endforeach</tbody></table></section><div class="mt-5">{{ $rows->links() }}</div>
    </div></div>
</x-app-layout>
